spring:
  datasource:
    url: ${DB_URL}
    driver-class-name: ${DB_DRIVER}
    username: ${DB_USER}
    password: ${DB_PASSWORD}


    hikari:
      maximum-pool-size: 20  # thread starvation 해결 제발
  jpa:
    database: mysql
    hibernate:
      ddl-auto: update
    #database-platform: org.hibernate.dialect.MySQL5Dialect
    #defer-datasource-initialization: true

    # 개발 초기 단계는 create 또는 update
    # 테스트 서버는 update 또는 validate
    # 스테이징과 운영 서버는 validate 또는 none

    show-sql: true
    properties:
      hibernate.format_sql: true

cloud:
  aws:
    region:
      static: ap-northeast-2
    s3:
      bucket: cookiee-s3
        # dir: S3 디렉토리 이름 # ex) /gyunny
    credentials:
      access-key: ${ACCESS_KEY}
      secret-key: ${SECRET_KEY}
    stack:
      auto: false

swagger:
  enabled: true
  base-package: com.cookiee.cookieeserver

  #custom:
  #s3url : ${s3url}

# 임시로 포트 번호 지정
#server:
  #port: 3306
#  servlet:
#    context-path: /cookiee