name: Build and Deploy SpringBoot to EC2

on:
  push:
    branches: [ "main" ]
    
env:
  PROJECT_NAME: cookiee-
  BUCKET_NAME: cookiee-cicde-bucket
  CODE_DEPLOY_APP_NAME: cookiee-cicd
  DEPLOYMENT_GROUP_NAME: cookiee_instance

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: "corretto"
          
      - name : Set up OPENAI.properties file
        run : echo "${{ secrets.DEV_OAUTH }}" > ./src/main/resources/application-oauth.yml
        shell : bash

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew
        shell: bash

      - name: Gradle Build
        run: ./gradlew build

      - name: Make Zip File
        run: zip -qq -r ./$GITHUB_SHA.zip .
        shell: bash
        
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_PRIVATE_ACCESS_KEY }}
          aws-region: ap-northeast-2

      - name: Set environment variables in application.yml
        run: |
          echo "DB_URL=${{ secrets.DB_URL }}" >> application.yml
          echo "DB_USER=${{ secrets.DB_USER }}" >> application.yml
          echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> application.yml
          echo "ACCESS_KEY=${{ secrets.ACCESS_KEY }}" >> application.yml
          echo "AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}" >> application.yml
          echo "AWS_PRIVATE_ACCESS_KEY=${{ secrets.AWS_PRIVATE_ACCESS_KEY }}" >> application.yml
          echo "JWT_ISSUER=${{ secrets.JWT_ISSUER }}" >> application.yml
          echo "JWT_SECRET_KEY=${{ secrets.JWT_SECRET_KEY }}" >> application.yml
          echo "SECRET_KEY=${{ secrets.SECRET_KEY }}" >> application.yml
      
      - name: Upload to S3
        run: aws s3 cp --region ap-northeast-2 ./$GITHUB_SHA.zip s3://$BUCKET_NAME/$PROJECT_NAME/$GITHUB_SHA.zip

      - name: Code Deploy To EC2 instance
        run: aws deploy create-deployment 
                --application-name $CODE_DEPLOY_APP_NAME 
                --deployment-config-name CodeDeployDefault.AllAtOnce
                --deployment-group-name $DEPLOYMENT_GROUP_NAME 
                --s3-location bucket=$BUCKET_NAME,bundleType=zip,key=$PROJECT_NAME/$GITHUB_SHA.zip
